modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="prettybeaches"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="prettybeaches.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "prettybeaches.mixins.json"
[[mixins]]
config = "prettybeaches.neoforge.mixins.json"
[[dependencies.prettybeaches]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.prettybeaches]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.prettybeaches]]
modId="balm"
type="required"
versionRange="[${balm_version},]"
ordering="NONE"
side="BOTH"
